language: php

php:
  - 7.0
  - 7.1

addons:
  apt:
    packages:
      - valgrind

install:
  - phpize
  - ./configure
  - make
  - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS="-q -m --show-diff" make test
  
